### ISSUE TITLE
"switch-case" and "else if"

### ISSUE THREAD

**Issue by ZILtoid1991** [Nafees10/qscript#9]
I'm going to use it in my game engine (PixelPerfectEngine) for general-purpose scripting, and mainly as embedded into the map files in a similar vain to PHP ("<?qscript [...] ?>"), or in external files.

I haven't found any references for such language features in the wiki, so I would like to ask if they will be implemented in the future?

**Comment by Nafees10** [comment]
I'm currently working on the `else if` part, you can see in the source that they've already been implemented in the AST generator.  
  
And sorry for the very late reply, school kept me busy.

**Comment by Nafees10** [comment]
I've added a small list of things, to readme, I'l be adding. If you have any other questions, feel free to ask.
